project:
  type: website

website:
  title: "**Bake Off** the Charts"
  navbar:
    background: "#FFB3C6"
    left:
      - href: index.qmd
        text: Home
      - crash-course.qmd
      - age.qmd
      - descriptions.qmd
      - more-graphs.qmd
      - about.qmd
      - sources.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true



